config/routes.rb
Enigma::Application.routes.draw do
  require_ssl = !Rails.env.development?
  scope :constraints => require_ssl ? { :protocol => "https" }  : {} do
    resources :events do
      get :scenario, :on=>:member
      resources :fixed_expenses
      resources :delegate_expenses
      resources :tickets do
        put :update_ticket_cost_details, :on=>:collection
      end
      resources :sponsors
    end

    devise_for :users

  end

  root :to=> redirect("/events")
  match "/*path", :to => redirect { |_, request| "https://" + request.host_with_port + request.fullpath } if require_ssl

end

app/models/event.rb
class Event
  include Mongoid::Document
  referenced_in :user
  field :name
  field :fixed_cost_per_ticket, :type=>Float, :default=>0.0
  field :percent_cost_per_ticket, :type=>Float, :default=>0.0
  field :default_sales, :type=>Integer

  validates_numericality_of :fixed_cost_per_ticket, :percent_cost_per_ticket
  validate :default_sales, :numericality=>true, :presence=>false

  validates_presence_of :name

  %w(delegate fixed).each do |type|
    embeds_many "#{type}_expenses" do
      def total
        self.sum(&:amount)
      end
    end
  end

  embeds_many :tickets
  embeds_many :sponsors do
    def total_price
      self.sum(&:price)
    end
    def total_tickets
      self.sum(&:number_of_tickets)
    end
  end

  def capacity
    tickets.sum(&:capacity)
  end

  def scenario_for(sales)
    Scenario.new(self, sales)
  end

  class Scenario
    attr_reader :tickets_sold, :sales, :ticket_cost, :sales_income
    def initialize(event, sales)
      @tickets_sold = {}
      @sales = sales
      @event = event
      @ticket_cost = 0
      @sales_income = 0
      count_tickets
    end
 

    def total_cost
      @event.fixed_expenses.total + delegate_cost + ticket_cost
    end

    def profit
      total_income - total_cost
    end

    def fixed_costs
      @event.fixed_expenses.total
    end

    def delegate_cost
      (@sales + @event.sponsors.total_tickets )* @event.delegate_expenses.total
    end

    def total_income
      sales_income + sponsorship_income
    end

    def sponsorship_income
      @event.sponsors.total_price
    end


    private
    def count_tickets
      tickets_unaccounted = @sales
      @event.tickets.sort_by(&:price).each do |ticket|
        sold = [ticket.capacity, tickets_unaccounted].min
        ticket_sales = sold * ticket.price
        @ticket_cost += sold * @event.fixed_cost_per_ticket
        @ticket_cost += ticket_sales * @event.percent_cost_per_ticket / 100
        @sales_income += ticket_sales 
        tickets_unaccounted -= sold
        @tickets_sold[ticket.name] = sold
      end
    end



  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def index
    @events = current_user.events
  end

  def show
    find_event
    scenario_for(@event.default_sales || @event.capacity * 0.8)
  end


  def scenario
    find_event
    @event.update_attribute(:default_sales, params[:sales])
    scenario_for(params[:sales])
    render :partial=>'scenario_result'
  end

  def create
    @event = current_user.events.create(params[:event])
    redirect_to :action=>:index
  end

private

  def find_event
    super(params[:id])
  end
  def scenario_for(sales)
    @scenario = @event.scenario_for(sales.to_i)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_scenario_result.html.haml
.sales
  %h4 Scenario for #{@scenario.sales} tickets sold
.tickets
  %table.tickets
    %thead
      %tr
        %th Ticket Type
        %th Price
        %th Sold
        %th Income
    %tbody
      -@event.tickets.each do |ticket|
        %tr
          %td.name=ticket.name
          %td.price=money(ticket.price)
          %td.sold= @scenario.tickets_sold[ticket.name]
          %td.income=money(ticket.price *  @scenario.tickets_sold[ticket.name])
      %tr
        %td.name='Sponsor'
        %td.price
        %td.sold=@event.sponsors.total_tickets
        %td.income

.summary
  %ul
    %li
      %span.summary_item Ticket Sales
      %span.summary_amount=money(@scenario.sales_income)
    %li
      %span.summary_item Sponsorship
      %span.summary_amount=money(@scenario.sponsorship_income)
    %li
      %span.summary_item Total income
      %span.summary_amount=money(@scenario.total_income)
  %ul
    %li
      %span.summary_item Cost of ticket sales
      %span.summary_amount=money(@scenario.ticket_cost)
    %li
      %span.summary_item  Fixed costs
      %span.summary_amount=money(@scenario.fixed_costs)
    %li
      %span.summary_item Delegate costs
      %span.summary_amount=money(@scenario.delegate_cost)
    %li
      %span.summary_item All costs
      %span.summary_amount=money(@scenario.total_cost)
  %ul
    %li.profit
      %span.summary_item Profit
      %span.summary_amount=money(@scenario.profit)

app/views/events/index.html.haml
%h2
  Events
%p=link_to "New Event", new_event_path
%ul.event_list
  - @events.each do |event|
    %li= link_to event.name, event_path(event)

app/views/events/new.html.haml
%h1 New Event
=form_for @event do |form|
  =form.text_field :name
  =form.submit

app/views/events/show.html.haml
=div_for @event do
  .event_name= "Event: #{@event.name}"
  .event_details.clearfix
    .detail
      =link_to "Tickets", event_tickets_path(@event)
      .value=@event.capacity
    .detail
      =link_to "Sponsors", event_sponsors_path(@event)
      .value=money(@event.sponsors.total_price)
    .detail
      =link_to "Fixed expenses", event_fixed_expenses_path(@event)
      .value= money(@event.fixed_expenses.total)
    .detail
      =link_to "Delegate expenses", event_delegate_expenses_path(@event)
      .value= money(@event.delegate_expenses.total)
  .scenario.clearfix
    %h3 Projections
    #ticket_sales
      Tickets:
      #ticket_slider_value=@scenario.sales
      #ticket_slider
        =image_tag "spinner.gif", :style=>"display:none;", :id=>'spinner'
      %p.description
        Use this slider to see your profit / loss amount for how many tickets you manage to sell.  (The assumption is that your cheapest tickets go first.)
    #scenario_result
      =render 'scenario_result'

:javascript
  jQuery('#ticket_slider').slider({
    max:#{@event.capacity},
    min:0,
    value:#{@scenario.sales},
    change: function(event, ui){
      $('#spinner').show();
      jQuery.get('#{scenario_event_path(@event.id)}?sales=' + ui.value, 
        function(scenario){
          jQuery('#scenario_result').html(scenario);
          $('#spinner').hide();
        })
      ;},
    slide: function(event, ui){jQuery('#ticket_slider_value').html(ui.value);}});