config/routes.rb
Enigma::Application.routes.draw do
  require_ssl = !Rails.env.development?
  scope :constraints => require_ssl ? { :protocol => "https" }  : {} do
    resources :events do
      get :scenario, :on=>:member
      resources :fixed_expenses
      resources :delegate_expenses
      resources :tickets do
        put :update_ticket_cost_details, :on=>:collection
      end
      resources :sponsors
    end

    devise_for :users

  end

  root :to=> redirect("/events")
  match "/*path", :to => redirect { |_, request| "https://" + request.host_with_port + request.fullpath } if require_ssl

end

app/models/sponsor.rb
class Sponsor
  include Mongoid::Document

  field :name
  field :price, :type=>Float
  field :number_of_tickets, :type=>Integer

  validates_presence_of :name, :price, :number_of_tickets
  validates_numericality_of :price, :number_of_tickets

  embedded_in :event, :inverse_of=>:sponsors
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_filter :find_sponsor
  def create
    @sponsor = Sponsor.new(params[:sponsor])
    if @sponsor.valid?
      @event.sponsors << @sponsor
      redirect_to({:action=>:index}, :notice=>'Sponsor added')
    else
      render :action=>:index
    end
  end

  def index
    @sponsor = Sponsor.new
  end

  def destroy 
    @sponsor.destroy
    redirect_to({:action=>:index}, :notice=>'Sponsor removed')
  end

  def edit
    
  end

  def show
    redirect_to :action=>:index
  end

  def update
    if @sponsor.update_attributes(params[:sponsor])
      redirect_to({:action=>:index}, :notice=>'Sponsor updated')
    else
      render :action=>:edit
    end
  end

  private
  def find_sponsor
    find_event
    @sponsor = @event.sponsors.find(params[:id]) if params[:id]
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
  def new_sponsor_style
    "display:none;" unless notice.present? || (@sponsor && !@sponsor.errors.empty?)
  end
end

app/views/sponsors/_form.html.haml
=semantic_form_for @sponsor, :url=>form_url do |form|
  =form.inputs do
    =form.input :name
    =form.money :price
    =form.input :number_of_tickets
  =form.buttons

app/views/sponsors/edit.html.haml
%h1 Edit sponsor #{link_to "Cancel", :back}
= render 'form', :form_url=>event_sponsor_path(@event.id, @sponsor.id)

app/views/sponsors/index.html.haml
%h1 #{link_to @event.name, event_path(@event)}: Sponsors
%p.description
  If you are lucky enough to have sponsors, you can account for the cost offset here. List each sponsor separately. Put the number of free tickets each sponsor receives down, as these will affect your per-delegate spending.
%h2= link_to_function "New Sponsor", "$('#new_sponsor').toggle('blind')"
#new_sponsor{:style=>new_sponsor_style}
  = render 'form', :form_url=>event_sponsors_path(@event)
%h2 Sponsors
-unless @event.sponsors.empty?
  %table.sponsors
    %thead
      %th Name
      %th Price
      %th Tickets
      %th
    %tbody
      -@event.sponsors.each do |sponsor|
        %tr{:class=>cycle('even', 'odd')}
          %td.name=sponsor.name
          %td.price=money(sponsor.price)
          %td.number_of_tickets=sponsor.number_of_tickets
          %td.edit
            =link_to edit_event_sponsor_path(@event.id, sponsor.id) do
              !=jquery_icon('pencil', 'Edit')
            =link_to event_sponsor_path(@event.id, sponsor.id),:method=>:delete, :confirm=>'Remove sponsor?' do
              !=jquery_icon('circle-minus', 'Delete')