config/routes.rb
Enigma::Application.routes.draw do
  require_ssl = !Rails.env.development?
  scope :constraints => require_ssl ? { :protocol => "https" }  : {} do
    resources :events do
      get :scenario, :on=>:member
      resources :fixed_expenses
      resources :delegate_expenses
      resources :tickets do
        put :update_ticket_cost_details, :on=>:collection
      end
      resources :sponsors
    end

    devise_for :users

  end

  root :to=> redirect("/events")
  match "/*path", :to => redirect { |_, request| "https://" + request.host_with_port + request.fullpath } if require_ssl

end

app/models/ticket.rb
class Ticket
  include Mongoid::Document

  field :price, :type=>Float
  field :name
  field :capacity, :type=>Integer

  validates_presence_of :name, :capacity, :price
  validates_numericality_of :capacity, :price
  embedded_in :event
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_event_and_tickets

  def index
    @ticket =  Ticket.new
  end


  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.valid?
      @event.tickets << @ticket
      redirect_to event_tickets_path(@event.id), :notice=>'Ticket created'
    else
      render :action=>:index
    end
  end



  def update
    @ticket.update_attributes params[:ticket]
    if @ticket.valid?
      @event.save
      redirect_to event_tickets_path(@event.id), :notice=>'Ticket updated'
    else
      render :action=>:edit
    end
  end

  def show
    redirect_to_index
  end

  def update_ticket_cost_details
    if @event.update_attributes(params[:event])
      redirect_to_index
    else
      @ticket = Ticket.new
      render :action=>:index
    end
  end

  def destroy
    @ticket.destroy
    redirect_to event_tickets_path(@event.id), :notice=>'Ticket removed'
  end

private
  def find_event_and_tickets
    find_event
    @ticket = @event.tickets.find(params[:id]) if params[:id]
  end

  def redirect_to_index
    redirect_to :action=>:index
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def new_ticket_style
    "display:none;" unless notice.present? || (@ticket && !@ticket.errors.empty?)
  end
end

app/views/tickets/_form.html.haml
=semantic_form_for @ticket , :url=>form_url do |form|
  =form.inputs do
    = form.input :name
    = form.money :price
    = form.input :capacity, :as=>:numeric
  =form.buttons

app/views/tickets/edit.html.haml
%h1 Edit ticket #{link_to "Cancel", :back}
= render 'form', :form_url=>event_ticket_path(@event.id, @ticket.id)

app/views/tickets/index.html.haml
%h1 #{link_to @event.name, event_path(@event)}: Tickets

%p.description
  Add all your ticket types here (eg early-bird, standard), remembering to include any "free tickets" such as organisers, speakers, helpers.

%h2= link_to_function "New Ticket", "jQuery('#new_ticket').toggle('blind')"
#new_ticket{:style=>new_ticket_style}
  = render 'form', :form_url=>event_tickets_path(@event)
%h2 Tickets
%table.tickets
  %thead
    %th Name
    %th Price
    %th Capacity
    %th
  %tbody
    -@event.tickets.each do |ticket|
      %tr{:class=>cycle('even', 'odd')}
        %td.name=ticket.name
        %td.price=money(ticket.price)
        %td.capacity=ticket.capacity
        %td.edit
          =link_to edit_event_ticket_path(@event.id, ticket.id) do
            !=jquery_icon('pencil', 'Edit')
          =link_to event_ticket_path(@event.id, ticket.id), :method=>:delete, :confirm=>'Delete ticket?' do
            != jquery_icon('circle-minus', 'Delete') 
%h2 Ticket overheads (payment processing fees, etc..)
=semantic_form_for @event, :url=>update_ticket_cost_details_event_tickets_path(@event) do |f|
  =f.inputs do
    =f.money :fixed_cost_per_ticket
    =f.input :percent_cost_per_ticket, :as=>:numeric
    =f.commit_button